version: '2'
services:
  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - '27017:27017'
  web:
    image: node:latest
    build: .
    ports:
      - '3000:3000'
    links:
      - mongodb
